swagger: "2.0"
info:
  version: "0.0.1"
  title: nodeTestApp16
# during dev, should point to your local machine
host: dockerHostIp:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /movies:
    # binds a127 app logic to a route
    x-swagger-router-controller: movies
    get:
      description: Returns a list of movies
      # used as the method name of the controller
      operationId: index
      parameters:
        - name: released
          in: query
          description: filters movies by released da
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/MoviesListBody"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    # get:
    #   description: Returns a list of movies
    #   # used as the method name of the controller
    #   operationId: readOne
    #   parameters:
    #     - name: released
    #       in: query
    #       description: filters the movie by released date
    #       type: string
    #   responses:
    #     "200":
    #       description: Success
    #       schema:
    #         # a pointer to a definition
    #         $ref: "#/definitions/MoviesListBody"
    #     # responses may fall through to errors
    #     default:
    #       description: Error
    #       schema:
    #         $ref: "#/definitions/ErrorResponse"
    post:
      description: Creates a new movie entry
      operationId: create
      parameters:
        - name: movie
          required: true
          in: body
          description: a new movies details
          schema:
            $ref: "#/definitions/MovieBody"
      responses:
        "200":
          description: Successfully stored movie details
          schema:
            $ref: "#/definitions/MovieBody"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /movies/{movieId}:
    x-swagger-router-controller: movies
    get:
      description: Returns a single movie entry by a given id 
      operationId: show
      parameters:
        - name: movieId
          required: true
          in: path
          type: string
      responses:
        "200":
          description: Successfully retrieved a movies details
          schema:
            $ref: "#/definitions/MovieBody"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Updates a single movie entry by a given id 
      operationId: update
      parameters:
        - name: movieId
          required: true
          in: path
          type: string
        - name: movie
          required: true
          in: body
          description: Details to be updated
          schema:
            $ref: "#/definitions/MovieBody"
      responses:
        "200":
          description: Successfully updated a movies details
          schema:
            $ref: "#/definitions/MovieBody"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Deletes a single movie entry by a given id
      operationId: delete
      parameters:
        - name: movieId
          required: true
          in: path
          type: string
      responses:
        "200":
          description: Successfully deleted a movies 
          schema:
            $ref: "#/definitions/MovieBody"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"



  /swagger:
    x-swagger-pipe: swagger_raw

# complex objects have schema definitions
definitions:
  MoviesListBody:
    required:
      - movies
    properties:
      movies:
        type: array
        items:
          $ref: "#/definitions/Movie"

  Movie:
    required:
      - tagline
      - title
      - released
    properties:
      tagline:
        type: string
      title:
        type: string
      released:
        type: integer
      rank:
        type: integer
        default: 5
        minimum: 1
        maximum: 10

  MovieBody:
    required:
      - movie
    properties:
      movie:
        $ref: "#/definitions/Movie"

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
